### ISSUE TITLE
Usability issues 

### ISSUE THREAD

**Issue by jonasKjellerup** [f-klubben/fappen#43]
This issue exists to track known usability issues on the current mobile demo.

---

- [x] Focusing an input causes the application to zoom in (IOS)
- [x] Many of the interactions you will typically do in the stregsystem module triggers text selection, which is kinda annoying (IOS; most likely also Android, but haven't confirmed)
- [x] It is not obvious thay you can click the cart at the bottom of the stregsystem page. Also help text on stregsytem page should be simplified.
- [x] Cart on stregsystem page is not properly fixed in location.
- [x] Links to external sites open in the application, meaning you can browse facebook from within the app, which is... not optimal.

**Comment by LowkeyCoding** [comment]
- [ ] Input field does not loss focus on submit (iOS)
