### ISSUE TITLE
Odd layout on my device (OP 6T)

### ISSUE THREAD

**Issue by krestenlaust** [f-klubben/fappen#63]
Something about the viewport is weird I think. I haven't tried to reproduce it using devtools yet.

![Screenshot_20231109-093414.jpg](https://github.com/f-klubben/fappen/assets/17174333/a1ccff66-2ae9-4a44-96e5-5bc5e324f8e4)

The purchase menu is different but not as bad, the fontsize is still odd
![Screenshot_20231109-093623.jpg](https://github.com/f-klubben/fappen/assets/17174333/811ab865-e95c-488c-a5fd-d8ff01071277)

(P.s. using PWA)

**Comment by jonasKjellerup** [comment]
It looks like you might have requested a desktop version in your browser. From what I can remember your browser settings are synced with the PWA instance. So try opening the page in your browser and see if you can switch it back to mobile view.

(I'm assuming that you are on Android)

**Comment by krestenlaust** [comment]
Yes, that solved it, thanks!
